version: "3.2"

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.5.1
    environment:
      - node.name=elasticsearch #https://www.elastic.co/guide/en/elasticsearch/reference/current/node.name.html
      - cluster.name="docker-cluster" # https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster.name.html
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
    networks:
      - elk

  kibana:
    container_name: kibana
    image: kibana:7.5.1
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true

  logstash:
    container_name: logstash
    image: logstash:7.5.1
   # command: logstash -f /usr/share/logstash/config/logstash.yml
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
      - BEATS_PORT=5044
      - ES_HOSTS=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    #  - path.config=null <- quebra geral!!!
    networks:
      - elk
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline/
        target: /usr/share/logstash/pipeline/
        read_only: true
    depends_on:
      - elasticsearch


  prometheus:
    image: prom/prometheus:v2.15.2
    container_name: prometheus
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - elk
    #restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "104" 
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:     
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring 
    networks:
      - elk
      
  


networks:
  elk:
    driver: bridge

volumes:
  spring_logs:

