# This is a basic workflow to help you get started with Actions

name: PushImageToDockerHub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: 
      - master
# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # log into docker hub account
      - name: Login to DockerHub
        run: | 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
      # get the date of the build
      - name: Get current date 
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')" 
      
      # push The image to the docker hub
      - name: Build the Docker image 
        run: docker build . --file ./Basic-task-3-2/Dockerfile3-2 --tag $DOCKER_USER/$REPO_NAME:latest

      - name: Docker Push
        run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
      


      
  